Alter session set "_oracle_script" = true;

CREATE ROLE adminTienda;
CREATE ROLE empleadoTienda;
CREATE ROLE clienteTienda;


CREATE USER adminTienda_user IDENTIFIED BY admin_password;
CREATE USER empleadoTienda_user IDENTIFIED BY empleado_password;
CREATE USER clienteTienda_user IDENTIFIED BY cliente_password;

GRANT adminTienda TO adminTienda_user;
GRANT empleadoTienda TO empleadoTienda_user;
GRANT clienteTienda TO clienteTienda_user;




CREATE PROFILE adminTienda_profile LIMIT
    SESSIONS_PER_USER UNLIMITED
    CPU_PER_SESSION 3000
    CPU_PER_CALL 1000
    CONNECT_TIME UNLIMITED
    IDLE_TIME UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED
    LOGICAL_READS_PER_CALL UNLIMITED
    PRIVATE_SGA UNLIMITED
    COMPOSITE_LIMIT UNLIMITED
    PASSWORD_LIFE_TIME 180
    PASSWORD_REUSE_TIME 90
    PASSWORD_REUSE_MAX 5
    PASSWORD_VERIFY_FUNCTION NULL;

CREATE PROFILE empleadoTienda_profile LIMIT
    SESSIONS_PER_USER UNLIMITED
    CPU_PER_SESSION 2000
    CPU_PER_CALL 800
    CONNECT_TIME UNLIMITED
    IDLE_TIME UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED
    LOGICAL_READS_PER_CALL UNLIMITED
    PRIVATE_SGA UNLIMITED
    COMPOSITE_LIMIT UNLIMITED
    PASSWORD_LIFE_TIME 90
    PASSWORD_REUSE_TIME 60
    PASSWORD_REUSE_MAX 3
    PASSWORD_VERIFY_FUNCTION NULL;

CREATE PROFILE clienteTienda_profile LIMIT
    SESSIONS_PER_USER 3
    CPU_PER_SESSION 1000
    CPU_PER_CALL 500
    CONNECT_TIME UNLIMITED
    IDLE_TIME UNLIMITED
    LOGICAL_READS_PER_SESSION UNLIMITED
    LOGICAL_READS_PER_CALL UNLIMITED
    PRIVATE_SGA UNLIMITED
    COMPOSITE_LIMIT UNLIMITED
    PASSWORD_LIFE_TIME 365
    PASSWORD_REUSE_TIME 180
    PASSWORD_REUSE_MAX 10
    PASSWORD_VERIFY_FUNCTION NULL;
