---Creacion de Table Spaces

--Tablesapce para datosl la mayoria de tablas estarán en este tablespace
CREATE TABLESPACE TBS_DATOS_PRINCIPALES
  DATAFILE 'C:\Oracle\ProyectoAdmin\DF_DATOS_PRINCIPALES.dbf'
  SIZE 100M
  DEFAULT STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);
  

  
  --Tablesapce para indeices
  CREATE TABLESPACE TBS_INDICES_TABLAS
  DATAFILE 'C:\Oracle\ProyectoAdmin\DF_INDICES_TABLAS.dbf'
  SIZE 50M
  DEFAULT STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);
  
  
  
  --Tablesapce para historicos
  CREATE TABLESPACE TBS_HISTORICO
  DATAFILE 'C:\Oracle\ProyectoAdmin\DF_HISTORICO.dbf'
  SIZE 200M
  DEFAULT STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);
  
  
  
  
ALTER TABLE Cliente MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE ProductoServicio MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Empleado MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Inventario MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Pedido MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Cotizacion MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Facturas MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE DetalleFactura MOVE TABLESPACE TBS_DATOS_PRINCIPALES;

ALTER TABLE Pais MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Provincia MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Canton MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Distrito MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE DetalleDireccion MOVE TABLESPACE TBS_DATOS_PRINCIPALES;

ALTER TABLE CategoriaProductoServicio MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Proveedor MOVE TABLESPACE TBS_DATOS_PRINCIPALES;


ALTER TABLE Departamento MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Salario MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Empleado MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE MetodoPago MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Pedido MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Cotizacion MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Facturas MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE DetalleFactura MOVE TABLESPACE TBS_DATOS_PRINCIPALES;

ALTER TABLE Venta MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Pedido MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE DetallePedido MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Cotizacion MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE CuentasPorCobrar MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE Envio MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE CampanaMarketing MOVE TABLESPACE TBS_DATOS_PRINCIPALES;
ALTER TABLE MetricaKPI MOVE TABLESPACE TBS_DATOS_PRINCIPALES;













  
  
  
  
  
  
  
  
  
  
  